[phases.setup]
nixPkgs = ["nss", "nspr", "atk", "cups", "dbus", "expat", "fontconfig", "freetype", "glib", "gtk3", "harfbuzz", "libdrm", "libgbm", "libxkbcommon", "mesa", "pango", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "xorg.libxcb"]
